version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@db/db_nork_town'
   
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: db_nork_town
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

